name: Update-JSON
run-name: Converting CSV to JSON
on: [push]
jobs:
  run-converter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pulling and Converting
        run: |
          cd data/
          python csv-to-json.py
          touch last-edited-at.time
      - name: Committing
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "VatII"
          pwd
#          git commit activity-data.json -m "Updated Info"
#          git commit last-edited-at.time -m "Timestamp"
      - name: Pushing
        run: |
          git push

      
  
